---

- name: Install docker package
  apt: 
    pkg: 
      - docker-ce
      - python3-pip
    state: present
    update_cache: yes

- name: Install docker-py package for python
  pip:
    name: docker-py

- name: Remove standart ssh port from ssh config
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: absent
    line: 'Port 22'

- name: Setup new standard port for ssh
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    line: 'Port 2222'

- name: Restart sshd service
  service: name=sshd state=restarted

- name: Download gitlab configs
  get_url:
    url: https://fmarkov-netology.s3.eu-central-1.amazonaws.com/gitlab
    dest: /tmp/gitlab.tar.gz.gpg
  
- name: Download runner configs
  get_url:
    url: https://fmarkov-netology.s3.eu-central-1.amazonaws.com/runner
    dest: /tmp/runner.tar.gz.gpg

- name: Decrypt and extract configs 
  shell: |
        cd /tmp
        gpg --batch --yes --passphrase {{ gitlab_root_pass }} \
        -o /tmp/gitlab.tar.gz \
        --decrypt /tmp/gitlab.tar.gz.gpg

        gpg --batch --yes --passphrase {{ gitlab_root_pass }} \
        -o /tmp/runner.tar.gz \
        --decrypt /tmp/runner.tar.gz.gpg

        tar -xvzf gitlab.tar.gz -C /
        tar -xvzf runner.tar.gz -C /

- name: Copy gitlab env file
  template: src=templates/gitlabrc dest=/etc/gitlabrc mode=444
